name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version you intend to release without leading 'v' (eg x.y.z and not vx.y.z)
  pull_request:
    types: [closed]
  push:
    branches:
      - "release/**"
      - "next/**"
    tags:
      - v*
  release:
    types: [created]

env:
  VERSION: ${{ github.event.inputs.version }}
  APP_ID: 251311

jobs:
  trigger-buf-setup-action-release:
    runs-on: ubuntu-latest
    steps:
      - name: trigger buf-setup-action release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: "joshcarp",
              repo: "buf-setup-action",
              workflow_id: "release.yaml",
              ref: "main",
              inputs: {
                version: "foobar"
              }
            })
